!function(t,e){"object"==typeof exports&&"undefined"!=typeof module?module.exports=e(require("ali-oss")):"function"==typeof define&&define.amd?define(["ali-oss"],e):(t="undefined"!=typeof globalThis?globalThis:t||self).AliOssUpload=e(t.OSS)}(this,(function(t){"use strict";
/*! *****************************************************************************
    Copyright (c) Microsoft Corporation.

    Permission to use, copy, modify, and/or distribute this software for any
    purpose with or without fee is hereby granted.

    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
    REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
    AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
    INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
    LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
    OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
    PERFORMANCE OF THIS SOFTWARE.
    ***************************************************************************** */function e(t,e,n,s){return new(n||(n=Promise))((function(o,i){function r(t){try{c(s.next(t))}catch(t){i(t)}}function a(t){try{c(s.throw(t))}catch(t){i(t)}}function c(t){var e;t.done?o(t.value):(e=t.value,e instanceof n?e:new n((function(t){t(e)}))).then(r,a)}c((s=s.apply(t,e||[])).next())}))}const n="STSTOKEN_NOT_SUPPLY",s="NOT_USE_STSTOKEN";var o;!function(t){t.zh="zh",t.en="en"}(o||(o={}));var i={[o.zh]:{[n]:"上传文件需要权限认证信息，需优先在实例化时提供异步方法asyncGetStsToken获取ststoken对象，或在调用upload方法时主动传入ststoken对象",[s]:"温馨提示：stsToken属于敏感信息，尽量不要直接明文暴露在代码中，防止误提交到线上，优先通过asyncGetStsToken异步方法生成stsToken😊"},[o.en]:{[n]:"Uploading files requires permission authentication information, and it is necessary to provide an asynchronous method asyncGetStsToken to obtain the ststoken object when instantiating, or actively pass in the ststoken object when calling the upload method.",[s]:"Reminder: stsToken is sensitive information, try not to directly expose the plain text in the code, to prevent mistaken submission to the line, first generate stsToken through the asyncGetStsToken asynchronous method.😊"}};return class{constructor(r){this.upload=o=>e(this,void 0,void 0,(function*(){const{directory:e,stsToken:r,file:a,extraUploadOptions:c,randomName:d=!1}=o;if(!r&&!this.asyncGetStsToken)throw new Error(i[this.language][n]);r&&console.warn(i[this.language][s]);const{name:h}=a;try{let n;if(r&&(n=this.getOssConfig(r)),this.asyncGetStsToken){const t=yield this.asyncGetStsToken();n=this.getOssConfig(t)}const s=new t(n),o=null!=c?c:this.defaultUploadOption,i=this.getConstructOssKey({name:h,directory:e,randomName:d}),u=yield s.multipartUpload(i,a,o);return this.domain?Object.assign({ossSrc:`${this.domain}${u.name}`},u):u}catch(t){console.error(t.message)}}));const{bucket:a,domain:c,region:d,directory:h="",extraUploadOptions:u={},asyncGetStsToken:l,log:y=!1,language:x=o.zh}=r;this.bucket=a,this.domain=c,this.directory=h,this.region=d,this.defaultUploadOption=u,this.asyncGetStsToken=l,this.log=y,this.language=x}handelDirectory(t){return""===t||"/"===t?"":t.replace(/^\/+|\/+$/g,"")+"/"}getConstructOssKey(t){const{directory:e=this.directory}=t,{name:n,randomName:s}=t,o=this.handelDirectory(e),i=n.split(".")[1];return s?"string"==typeof s?`${o}${s}.${i}`:`${o}${this.getUuid()}.${i}`:`${o}${n}`}getUuid(){return"xxxxxxxxxxxx4xxxyxxxxxxxxxxxxxxx".replace(/[xy]/g,(t=>{const e=16*Math.random()|0;return("x"==t?e:3&e|8).toString(16)}))}getOssConfig(t){const{accessKeyId:e,accessKeySecret:n,securityToken:s}=t;return{secure:!0,region:this.region,accessKeyId:e,accessKeySecret:n,stsToken:s,bucket:this.bucket}}}})),"undefined"!=typeof window&&(window._ALI_OSS_UPLOAD_VERSION_="1.0.2");
